<a href="https://colab.research.google.com/github/khalida2025cse-sudo/FDS_Lab_Experiments/blob/main/Exp_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Country": [
        "India", "USA", "UK", "India", "Canada",
        "USA", "India", np.nan, "UK", "Canada"
    ],

    "Age": [
        22, 25, np.nan, 31, 28,
        35, 24, 40, np.nan, 30
    ],

    "Salary": [
        35000, 50000, 45000, np.nan, 60000,
        55000, 42000, 70000, 48000, np.nan
    ],

    "Purchased": [
        "Yes", "No", "Yes", "No", "Yes",
        "No", "Yes", "Yes", "No", "Yes"
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Dataset Information:")
df.info()

print("Mode of Country:")
print(df["Country"].mode())

# Fill missing Country with Mode
df["Country"] = df["Country"].fillna(df["Country"].mode()[0])

# Fill missing Age with Median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Salary with Mean
df["Salary"] = df["Salary"].fillna(round(df["Salary"].mean()))

print("After Data Preprocessing:")
display(df)

Original Dataset:

  Country   Age   Salary Purchased
0   India  22.0  35000.0       Yes
1     USA  25.0  50000.0        No
2      UK   NaN  45000.0       Yes
3   India  31.0      NaN        No
4  Canada  28.0  60000.0       Yes
5     USA  35.0  55000.0        No
6   India  24.0  42000.0       Yes
7     NaN  40.0  70000.0       Yes
8      UK   NaN  48000.0        No
9  Canada  30.0      NaN       Yes

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      object
 1   Age        8 non-null      float64
 2   Salary     8 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes
Mode of Country:
0    India
Name: Country, dtype: object
After Data Preprocessing:

  Country   Age   Salary Purchased
0   India  22.0  35000.0       Yes
1     USA  25.0  50000.0        No
2      UK  29.0  45000.0       Yes
3   India  31.0  50625.0        No
4  Canada  28.0  60000.0       Yes
5     USA  35.0  55000.0        No
6   India  24.0  42000.0       Yes
7   India  40.0  70000.0       Yes
8      UK  29.0  48000.0        No
9  Canada  30.0  50625.0       Yes